#!/usr/bin/env python3
"""crux views — fully-generated, never hand-edited.

render_meta       -> META.md       : project header + the live question/idea tree + a status dashboard
render_experiments-> EXPERIMENTS.md : a flat registry, one row per hypothesis

Both are pure functions of the vault's nodes (no timestamps, no volatile data),
so re-rendering is byte-stable / idempotent.
"""
import re
from engine import VERDICTS

_STATUS_MARK = {
    "open": "○", "review": "◐", "resolved": "●",
    "idea": "·", "staged": "▷", "running": "▶", "done": "✓",
}

def _count_runs(node):
    n, in_sec = 0, False
    for line in node["body"].splitlines():
        if line.startswith("## "):
            in_sec = line.strip().lower() == "## run links"
            continue
        if in_sec and re.match(r"\s*- (?!_\(none)", line):
            n += 1
    return n

def render_meta(v):
    cfg = v.cfg
    out = [f"# {cfg['title']} — research notebook",
           "",
           "_Generated by `crux`. Do not edit by hand — run any crux command to refresh._",
           "",
           f"Root: [[{v.root_node().basename}]]",
           "",
           "## Question tree",
           ""]

    def walk(nid, depth):
        n = v.nodes[nid]
        if n.type == "project":
            for c in v.children.get(nid, []):
                walk(c, depth)
            return
        mark = _STATUS_MARK.get(n.status, "·")
        label = f"**{n.title}**" if n.type == "question" else n.title
        extra = ""
        if n.type == "idea" and n["fm"].get("verdict"):
            extra = f" — _{n['fm']['verdict']}_"
            if n["fm"].get("metric"):
                extra += f" (`{n['fm']['metric']}`)"
        kind = "Q" if n.type == "question" else "H"
        out.append("  " * depth + f"- {mark} `{n.id}` [{kind}] [[{n.basename}|{label}]] — *{n.status}*{extra}")
        for c in v.children.get(nid, []):
            walk(c, depth + 1)

    walk(cfg["root_id"], 0)

    # dashboard
    qs = [n for n in v.nodes.values() if n.type == "question"]
    ideas = [n for n in v.nodes.values() if n.type == "idea"]
    qstat = {s: sum(1 for n in qs if n.status == s) for s in ("open", "review", "resolved")}
    istat = {s: sum(1 for n in ideas if n.status == s) for s in ("idea", "staged", "running", "done")}
    vstat = {x: sum(1 for n in ideas if n["fm"].get("verdict") == x) for x in VERDICTS}
    out += ["", "## Dashboard", "",
            f"- **Questions** ({len(qs)}): open {qstat['open']} · review {qstat['review']} · resolved {qstat['resolved']}",
            f"- **Hypotheses** ({len(ideas)}): idea {istat['idea']} · staged {istat['staged']} · running {istat['running']} · done {istat['done']}",
            f"- **Verdicts**: supported {vstat['supported']} · partial {vstat['partial']} · refuted {vstat['refuted']} · inconclusive {vstat['inconclusive']}"]
    review_q = [n for n in qs if n.status == "review"]
    if review_q:
        out += ["", "## ⚠ Awaiting your decision (`review`)", ""]
        out += [f"- `{n.id}` [[{n.basename}|{n.title}]]" for n in review_q]
    return "\n".join(out).rstrip() + "\n"

def render_experiments(v):
    ideas = sorted((n for n in v.nodes.values() if n.type == "idea"),
                   key=lambda n: (int(re.sub(r"\D", "", n.id) or 0)))
    out = ["# Experiments — registry",
           "",
           "_Generated by `crux`. One row per hypothesis. Do not edit by hand._",
           "",
           "| id | hypothesis | question | status | verdict | metric | runs |",
           "|----|------------|----------|--------|---------|--------|------|"]
    for n in ideas:
        q = v.nodes.get(n.parent)
        qlabel = f"[[{q.basename}\\|{q.id}]]" if q else "—"
        out.append(f"| `{n.id}` | [[{n.basename}\\|{n.title}]] | {qlabel} | {n.status} | "
                   f"{n['fm'].get('verdict') or '—'} | {n['fm'].get('metric') or '—'} | {_count_runs(n)} |")
    if not ideas:
        out.append("| — | _no hypotheses yet_ | | | | | |")
    return "\n".join(out).rstrip() + "\n"
